name = "mission-chat"
main = "index.js"
compatibility_date = "2026-02-28"

# Durable Object Binding
[[durable_objects.bindings]]
name = "MISSION_CHAT"
class_name = "Mission_Chat"

# Required for SQLite-backed Durable Object
[[migrations]]
tag = "v1"
new_sqlite_classes = ["Mission_Chat"]